/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-south-1",
  aws_cognito_identity_pool_id:
    "ap-south-1:9064e981-d211-4376-a2c3-7748070054d7",
  aws_cognito_region: "ap-south-1",
  aws_user_pools_id: "ap-south-1_PLy7AdFgv",
  aws_user_pools_web_client_id: "5i4dqmi3eho1mtd2vf62qdtkao",
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["NAME", "PHONE_NUMBER"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["PHONE_NUMBER"],
  aws_cloud_logic_custom: [
    {
      name: "restAuthApi",
      endpoint: "https://48zpzd5169.execute-api.ap-south-1.amazonaws.com/dev",
      region: "ap-south-1",
    },
    {
      name: "AdminQueries",
      endpoint: "https://jy79vqifhi.execute-api.ap-south-1.amazonaws.com/dev",
      region: "ap-south-1",
    },
    {
      name: "AdvoApis",
      endpoint: "https://jza2nkfge1.execute-api.ap-south-1.amazonaws.com/dev",
      region: "ap-south-1",
    },
  ],
  aws_mobile_analytics_app_id: "cd89a5747d0b4085b116ff577d04c0a0",
  aws_mobile_analytics_app_region: "ap-south-1",
};


export default awsmobile;
